<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>gulp on ebullient·works</title><link>/tags/gulp.html</link><description>Recent content in gulp on ebullient·works</description><generator>Hugo -- gohugo.io</generator><language>en-us</language><lastBuildDate>Thu, 20 Sep 2018 00:00:00 +0000</lastBuildDate><atom:link href="/tags/gulp/index.xml" rel="self" type="application/rss+xml"/><item><title>Debug gulp</title><link>/2018/09/20/debug-gulp.html</link><pubDate>Thu, 20 Sep 2018 00:00:00 +0000</pubDate><guid>/2018/09/20/debug-gulp.html</guid><description>&lt;p>A gulp build unhelpfully finished with:&lt;/p>
&lt;pre tabindex="0">&lt;code>(node:12030) UnhandledPromiseRejectionWarning: null
(node:12030) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12030) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
&lt;/code>&lt;/pre>&lt;p>I needed to change both my gulpfile and my IDE to be able to follow what
was happening.&lt;/p></description></item></channel></rss>